config/routes.rb
AirHockeyWebService::Application.routes.draw do
  resources :user_takasus

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :point, :email, :reward
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: {with: VALID_EMAIL_REGEX}
  default_scope order: 'users.point DESC'
end

app/models/user_takasu.rb
class UserTakasu < ActiveRecord::Base
  attr_accessible :name, :point
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/user_takasus_controller.rb
class UserTakasusController < ApplicationController
  # GET /user_takasus
  # GET /user_takasus.json
  def index
    @user_takasus = UserTakasu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_takasus }
    end
  end

  # GET /user_takasus/1
  # GET /user_takasus/1.json
  def show
    @user_takasu = UserTakasu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_takasu }
    end
  end

  # GET /user_takasus/new
  # GET /user_takasus/new.json
  def new
    @user_takasu = UserTakasu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_takasu }
    end
  end

  # GET /user_takasus/1/edit
  def edit
    @user_takasu = UserTakasu.find(params[:id])
  end

  # POST /user_takasus
  # POST /user_takasus.json
  def create
    point_new = params[:point]
    if User.all.count >= 10
      point = User.first.point
      user = User.first
      User.all.each do |u|
        if u.point < point
          user = u
          point = u.point
        end
      end
      if user.point < point_new.to_i
        user.destroy
        @user = User.new(name: params[:name], point: params[:point])
        respond_to do |format|
          if @user.save
            format.html { redirect_to @users, notice: 'User was successfully created.' }
            format.json { render json: @users, status: :created, location: @user }
          else
            format.html { render action: "new" }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end 
      end
    else
      @user = User.new(name: params[:name], point: params[:point])
        respond_to do |format|
          if @user.save
            format.html { redirect_to @users, notice: 'User was successfully created.' }
            format.json { render json: @users, status: :created, location: @user }
          else
            format.html { render action: "new" }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
    end
  end

  # PUT /user_takasus/1
  # PUT /user_takasus/1.json
  def update
    @user_takasu = UserTakasu.find(params[:id])

    respond_to do |format|
      if @user_takasu.update_attributes(params[:user_takasu])
        format.html { redirect_to @user_takasu, notice: 'User takasu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_takasu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_takasus/1
  # DELETE /user_takasus/1.json
  def destroy
    @user_takasu = UserTakasu.find(params[:id])
    @user_takasu.destroy

    respond_to do |format|
      format.html { redirect_to user_takasus_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    user_first = User.where(name: params[:name], point: params[:point].to_i)
    if user_first.first != nil
      respond_to do |format|
        user_first.first.email = params[:email]
        if user_first.first.save
          if user_first.first.reward != 0
            UserMailer.welcome_email(user_first.first).deliver
            user_first.first.reward = 0
            user_first.first.save
          end
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      point_new = params[:point]
    if User.all.count >= 10
      point = User.first.point
      point_max = User.first.point
      user = User.first
      user_max = User.first
      User.all.each do |u|
        if u.point < point
          user = u
          point = u.point
        elsif u.point > point_max
          user_max = u
          point_max = u.point
        end
      end

      if user.point < point_new.to_i
        user.destroy
        @user = nil
        if point_new.to_i > user_max.point
          @user = User.new(name: params[:name], point: params[:point],
            email: params[:email], reward: 1)
        else
          @user = User.new(name: params[:name], point: params[:point],
            email: params[:email], reward: params[:reward])
        end
        respond_to do |format|
          if @user.save
            format.html { redirect_to @users, notice: 'User was successfully created.' }
            format.json { render json: @users, status: :created, location: @user }
          else
            format.html { render action: "new" }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end 
      end
    else
      @user = User.new(name: params[:name], point: params[:point], email: params[:email])
        respond_to do |format|
          if @user.save
            format.html { redirect_to @users, notice: 'User was successfully created.' }
            format.json { render json: @users, status: :created, location: @user }
          else
            format.html { render action: "new" }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
    end
    end 
  end
  
  def updateEmail
    binding.pry
  end
  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_takasus_helper.rb
module UserTakasusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirHockeyWebService</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_takasus/_form.html.erb
<%= form_for(@user_takasu) do |f| %>
  <% if @user_takasu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_takasu.errors.count, "error") %> prohibited this user_takasu from being saved:</h2>

      <ul>
      <% @user_takasu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :point %><br />
    <%= f.number_field :point %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_takasus/edit.html.erb
<h1>Editing user_takasu</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_takasu %> |
<%= link_to 'Back', user_takasus_path %>

app/views/user_takasus/index.html.erb
<h1>Listing user_takasus</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Point</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_takasus.each do |user_takasu| %>
  <tr>
    <td><%= user_takasu.name %></td>
    <td><%= user_takasu.point %></td>
    <td><%= link_to 'Show', user_takasu %></td>
    <td><%= link_to 'Edit', edit_user_takasu_path(user_takasu) %></td>
    <td><%= link_to 'Destroy', user_takasu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User takasu', new_user_takasu_path %>

app/views/user_takasus/new.html.erb
<h1>New user_takasu</h1>

<%= render 'form' %>

<%= link_to 'Back', user_takasus_path %>

app/views/user_takasus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user_takasu.name %>
</p>

<p>
  <b>Point:</b>
  <%= @user_takasu.point %>
</p>


<%= link_to 'Edit', edit_user_takasu_path(@user_takasu) %> |
<%= link_to 'Back', user_takasus_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :point %><br />
    <%= f.number_field :point %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Point</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.point %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Point:</b>
  <%= @user.point %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>